service: codenity-day-node

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:
  codenityDay:
    handler: src/handlers/handler.handlerCodenity
    name: handlerCodenityDay

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket
  - serverless-offline
  - serverless-iam-roles-per-function